namespace OffsetBased.PageRequestGenerationHandling;

/// <inheritdoc />
/// <remarks>
/// Page requests are generated by generating a base request via a request factory and then adding the pagination
/// parameters to the request URI, as well as combining the base URI with the request URI.
/// </remarks>
[PublicAPI]
public class PageRequestGeneratorViaRequestFactory : PageRequestGeneratorViaAsyncRequestFactory
{
    /// <summary>
    /// Initializes a new instance of the <see cref="PageRequestGeneratorViaRequestFactory"/> class.
    /// </summary>
    /// <param name="makeRequest">The factory to create the base request.</param>
    /// <param name="paginationParametersConfiguration">The configuration for the pagination parameters.</param>
    public PageRequestGeneratorViaRequestFactory(
        Func<HttpRequestMessage> makeRequest,
        PaginationParametersConfiguration paginationParametersConfiguration)
        : base(_ => Task.FromResult(makeRequest()), paginationParametersConfiguration)
    {
    }
}
