namespace OffsetBased.PageRequestGenerationHandling;

/// <inheritdoc />
/// <remarks>
/// Page requests are generated by generating a base request as a get request to a resource and then adding the
/// pagination parameters to the request URI, as well as combining the base URI with the request URI.
/// </remarks>
[PublicAPI]
public class PageRequestGeneratorViaResource : PageRequestGeneratorViaRequestFactory
{
    /// <summary>
    /// Initializes a new instance of the <see cref="PageRequestGeneratorViaResource"/> class.
    /// </summary>
    /// <param name="resource">The resource to generate the base request for.</param>
    /// <param name="paginationParametersConfiguration">The configuration for the pagination parameters.</param>
    public PageRequestGeneratorViaResource(
        string resource,
        PaginationParametersConfiguration paginationParametersConfiguration)
        : base(RequestFactory(resource), paginationParametersConfiguration)
    {
    }

    private static Func<HttpRequestMessage> RequestFactory(string resource)
        => () => new(HttpMethod.Get, resource);
}
