# This GitHub Actions workflow, named ".NET Test", is designed to be called by other workflows.
# It defines a single job named "test" that runs on an Ubuntu environment.
# This job checks out the repository's code, sets up .NET version 9,
# and then executes the `dotnet test` command in Release configuration to run the project's tests.
name: .NET Test

on:
  workflow_call:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
      - name: Run tests
        run: dotnet test --configuration Release
