# This GitHub Actions workflow, named ".NET Build and Test", is designed to be called by other workflows.
# It defines a single job that runs on an Ubuntu environment.
# This job checks out the repository's code, sets up .NET version 9,
# explicitly builds the entire solution (including sample projects) to catch build errors,
# and then executes the tests in Release configuration.
name: .NET Build and Test

on:
  workflow_call:

jobs:
  build_and_test:
    name: Build solution and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9
      # Explicitly build the entire solution first to catch any build errors,
      # including in sample projects that aren't built as part of the test dependencies.
      # This ensures that broken sample projects cannot be merged, as they would
      # previously pass CI since tests don't depend on sample projects.
      - name: Build solution
        run: dotnet build Pagination.slnx --configuration Release
      - name: Run tests
        run: dotnet test Pagination.slnx --configuration Release --no-build
